defmodule EhsEnforcement.Repo.Migrations.DropAirtableIdFromNotices do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:notices) do
      remove :airtable_id
    end
  end

  def down do
    alter table(:notices) do
      add :airtable_id, :text
    end
  end
end
