defmodule EhsEnforcement.Repo.Migrations.AddLegislationGovUkFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists index(
                     :legislation,
                     [:legislation_title, :legislation_year, :legislation_number],
                     name: "legislation_title_year_number_unique"
                   )

    alter table(:legislation) do
      modify :legislation_number, :text
      add :legislation_type_code, :text
      add :legislation_url, :text
    end

    create index(:legislation, [:legislation_type_code], name: "legislation_type_code_index")

    create index(:legislation, [:legislation_title, :legislation_year, :legislation_number],
             name: "legislation_title_year_number_unique",
             unique: true,
             where: "legislation_type_code IS NULL"
           )

    create index(:legislation, [:legislation_year, :legislation_number, :legislation_type_code],
             name: "legislation_gov_uk_unique",
             unique: true,
             where:
               "legislation_year IS NOT NULL AND legislation_number IS NOT NULL AND legislation_type_code IS NOT NULL"
           )

    create unique_index(
             :legislation,
             [:legislation_year, :legislation_number, :legislation_type_code],
             name: "legislation_unique_gov_uk_index",
             nulls_distinct: false
           )
  end

  def down do
    drop_if_exists unique_index(
                     :legislation,
                     [:legislation_year, :legislation_number, :legislation_type_code],
                     name: "legislation_unique_gov_uk_index"
                   )

    drop_if_exists index(
                     :legislation,
                     [:legislation_year, :legislation_number, :legislation_type_code],
                     name: "legislation_gov_uk_unique"
                   )

    drop_if_exists index(
                     :legislation,
                     [:legislation_title, :legislation_year, :legislation_number],
                     name: "legislation_title_year_number_unique"
                   )

    drop_if_exists index(:legislation, [:legislation_type_code],
                     name: "legislation_type_code_index"
                   )

    alter table(:legislation) do
      remove :legislation_url
      remove :legislation_type_code
      modify :legislation_number, :bigint
    end

    create index(:legislation, [:legislation_title, :legislation_year, :legislation_number],
             name: "legislation_title_year_number_unique",
             unique: true
           )
  end
end
