defmodule EhsEnforcement.Repo.Migrations.AddFraNoticeFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:notices) do
      add :notice_status, :text
      add :premises_type, :text
    end
  end

  def down do
    alter table(:notices) do
      remove :premises_type
      remove :notice_status
    end
  end
end
